### ISSUE TITLE
dymmatrix.py problem

### ISSUE THREAD

**Issue by sean8cal** [raman-sc/VASP#2]
I am trying to calculate a Raman spectra and am following the example of Bulk Silicon using the VTST tools. I am getting this feedback after submitting the dymmatrix.py script after the vibrational calculations step:

```
Reading DISPLACECAR
Traceback (most recent call last):
  File "/home/sdix/scripts/dymmatrix.py", line 135, in <module>
    dymmatrix(displacecars, outcars)
  File "/home/sdix/scripts/dymmatrix.py", line 29, in dymmatrix
    ndisp = numpy.count_nonzero(displacements)
AttributeError: 'module' object has no attribute 'count_nonzero'
```

I have tried a few different DISPLACECARS but I can not resolve this issue.

**Comment by afonari** [comment]
Probably your numpy is too old. To get numpy version:
```
import numpy
numpy.version.version
```

**Comment by sean8cal** [comment]
This solved the problem. Thank you
